import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    certis: [
      { name: 'DANIELA  GARAVITO CÁMARA', id: 28607 },
      { name: 'DANIEL  RODRÍGUEZ CUSI', id: 16371 },
      { name: 'QUENIA DELITZER  GUARY SOTTO ', id: 10672 },
      { name: 'JENNY CATALINA PINTO GUTIERREZ', id: 12709 },
      { name: 'EVEN BORIS  MAGNE BORDA ', id: 10947 },
      { name: 'LIMBER  LEON RIOS ', id: 16212 },
      { name: 'GRACIELA  LAURA AMARU ', id: 10602 },
      { name: 'MAURA  MUÑOZ HUALLPA ', id: 17779 },
      { name: 'EYDNAR  HUANCA TORREZ ', id: 21835 },
      { name: 'MARIA DEL CARMEN RAMIREZ DUCHEN', id: 25612 },
      { name: 'WILSON FLORES LIMACHI', id: 20196 },
      { name: 'EDWIN JAVIER  DE LA FUENTE SAAVEDRA ', id: 15265 },
      { name: 'VIVIANA CONDE SARCO', id: 26369 },
      { name: 'DORIS ROJAS BECERRA', id: 16167 },
      { name: 'KAREN MORALES SANABRIA', id: 12613 },
      { name: 'GRACIELA LAURA AMARU', id: 29929 },
      { name: 'VERÓNICA CONSUELO  LUQUE FLORES ', id: 23868 },
      { name: 'JUAN PABLO REJAS BAPTISTA', id: 21550 },
      { name: 'NILFOR NADIO  HUARACHI LEANDRO ', id: 11804 },
      { name: 'CAROL RAQUEL ALANOCA MAMANI', id: 10774 },
      { name: 'NOHELIA MERCADO', id: 20908 },
      { name: 'MARIO  QUISPE ALFARO', id: 14705 },
      { name: 'MARIELA  RUEDA VALENCIA ', id: 15652 },
      { name: 'RUHT GABRIELA CASAZOLA FERNADEZ', id: 21869 },
      { name: 'REYMUNDO GUZMAN ACERO ', id: 16597 },
      { name: 'EVELYN MAMANI CABEZAS', id: 14999 },
      { name: 'JUAN BERNABÉ BELTRÁN ALAVE', id: 28112 },
      { name: 'ELMER GONZALO  MAMANI LEÓN', id: 28050 },
      { name: 'RINA MARTHA VISCARRA ZEGARRA', id: 11582 },
      { name: 'FILIBERTO MAMANI  ALVAREZ', id: 10863 },
      { name: 'SARA ROCIO DÍAZ QUISPE', id: 23474 },
      { name: 'KARINA SHIRLEY AGUILAR UNZUETA', id: 21200 },
      { name: 'GIOVANA  CALISAYA COLQUEHUANCA', id: 18123 },
      { name: 'TONNY CRISTHIAN FERNANDEZ CASTRO', id: 22587 },
      { name: 'KATHERINE FABIOLA  FLORES LAURA ', id: 19425 },
      { name: 'ROXANA  ALVAREZ ALBAREZ', id: 12125 },
      { name: 'DRA. MARIA DEL CARMEN  SARAVIA CARDOZO', id: 14961 },
      { name: 'DARIO OBIS MITMA CHOQUECALLATA', id: 14602 },
      { name: 'GIANNA ERIKA  MONTENEGRO BEJARANO ', id: 19850 },
      { name: 'CARLA MERCEDES  ORTIZ CABRERA ', id: 28086 },
      { name: 'JOSÉ ELIO  GABRIEL LÓPEZ ', id: 17784 },
      { name: 'ARMANDO VACA CITA', id: 16959 },
      { name: 'KATHIA SUSAN ANCIETA RIOS', id: 23181 },
      { name: 'ESTANISLAO FRANCO RAMIREZ SANABRIA', id: 26708 },
      { name: 'ANA GRACIELA  CRUZ GARCIA ', id: 23738 },
      { name: 'JOSE LUIS GUARANA FLORES', id: 11610 },
      { name: 'CARMEN MERCEDES CALDERON QUISPE', id: 17584 },
      { name: 'BOZENA IRENA MISIAK', id: 23248 },
      { name: 'ROLANDO VARGAS MARTINEZ', id: 16777 },
      { name: 'HANS MEDINA MORALES', id: 20744 },
      { name: 'ANA MARÍA  TEJADA PACHECO ', id: 20375 },
      { name: 'SANDRA SANDOVAL MONTAÑO', id: 10074 },
      { name: 'EDITH URQUIDI OSINA ', id: 29529 },
      { name: 'KEVIN DANIEL ROJAS', id: 21590 },
      { name: 'JIMENA ALEJANDRA PUYAL PEREZ', id: 25823 },
      { name: 'JULIO JORDAN ALEJO MAMANI', id: 24773 },
      { name: 'TERESA ELIZABETH  ARENAS VILLA ', id: 26921 },
      { name: 'GHELY MARBEL VILLCA GUZMAN', id: 24957 },
      { name: 'ALBERTO SEBASTIÁN  ESCALIER TORREJON ', id: 22828 },
      { name: 'NELIDA  MARTINEZ BARRETO', id: 16394 },
      { name: 'MARCO ANTONIO  CHUMACERO LOPEZ', id: 27001 },
      { name: 'JUAN TITO  ARUQUIPA ACHU', id: 13220 },
      { name: 'WILMER  CONDORI SARZURI ', id: 11982 },
      { name: 'ANA MARIBEL MAMANI YUJRA', id: 28173 },
      { name: 'ERASMO RAMOS ARUQUIPA ', id: 25159 },
      { name: 'JHANNET BENIGNA  HILARI ARUQUIPA', id: 17571 },
      { name: 'LEIDY JIMENEZ SILES', id: 10109 },
      { name: 'VICTOR HUGO LOAYZA MAMANI', id: 19398 },
      { name: 'MELVY TALAVERA MENACHO', id: 19399 },
      { name: 'OLVIS ESCALANTE MEJIA', id: 24009 },
      { name: 'WILLY WALTER QUISPE TICONA', id: 19628 },
      { name: 'RUFINO  CALLISAYA   CASTRO', id: 29168 },
      { name: 'ISABEL  MENESES CABEZAS ', id: 26375 },
      { name: 'MARÍA TERESA  CABEZAS GALARZA', id: 12951 },
      { name: 'LILIANA MENESES CABEZAS ', id: 19952 },
      { name: 'EDDY JOHN MILLARES CHAO', id: 20385 },
      { name: 'IVAN CALCINA HUAYHUA', id: 10539 },
      { name: 'EDUARDO EDWIN SOLÍS SILES', id: 18226 },
      { name: 'SONIA ROXANA  LOPEZ MIRANDA', id: 28624 },
      { name: 'NANCY NOEMI QUISPE PERCA', id: 13637 },
      { name: 'MIRIAM CORINA  HUARACHI LEANDRO', id: 22099 },
      { name: 'BLANCA MAGALI ARENAS VILLA', id: 17845 },
      { name: 'LUZ ELENA  APAZA NISTAZA ', id: 20977 },
      { name: 'ESCARLIE VIVIAN GUTIÉRREZ SOLIZ', id: 27484 },
      { name: 'YOSELYN ABIGAIL  VARGAS VILLAMIL', id: 13367 },
      { name: 'LUIS ERNESTO MEDRANO CORAZÓN', id: 21132 },
      { name: 'SHIRLEY GUTIERREZ AÑEZ', id: 28896 },
      { name: 'RENE CRISTIAN ROJAS VARGAS', id: 24196 },
      { name: 'SIRLEY  MORALES ONTIVEROS ', id: 17673 },
      { name: 'FREDY  RODRÍGUEZ RODRÍGUEZ ', id: 14639 },
      { name: 'NELLY ROSALBA ARNEZ MIRANDA', id: 21566 },
      { name: 'ILDA  CONDORI RUEDA ', id: 18150 },
      { name: 'NANCY NÚÑEZ CHUMACERO', id: 10139 },
      { name: 'MIRIAM FÁTIMA  IBAÑEZ LUNA ', id: 12697 },
      { name: 'ARIEL BALDERRAMA ROCHA', id: 24121 },
      { name: 'ERWIN MAMANI MAMANI', id: 17835 },
      { name: 'ERASMO  RAMOS ARUQUIPA ', id: 25475 },
      { name: 'ROSIO DEL PILAR HERRERA ADUVIRI', id: 27596 },
      { name: 'SOFIA  VILLALPANDO CUISA ', id: 13704 },
      { name: 'LUZ MARINA MORON', id: 21827 },
      { name: 'NAIRA ROJAS SALGUERO', id: 24321 },
      { name: 'OSVALDO VILDOZO VILLAMONTE', id: 29018 },
      { name: 'JOSE LINO LOAYZA CASTRO ', id: 26681 },
      { name: 'BOZENA IRENA APELLIDO PATER.:  MISIAK', id: 14107 },
      { name: 'TEOLINDA AMAZA NOCRE', id: 16758 },
      { name: 'MARTHA VERONICA TORREZ ARDAYA', id: 22754 },
      { name: 'LUZ MARINA  MORON', id: 15627 },
      { name: 'PATRICIA  ALMENDRAS CALIZAYA ', id: 24753 },
      { name: 'ANDREA MARIBEL  JAIMES RIVERA', id: 29268 },
      { name: 'ING. FERNANDO  GUARACHI ALIAGA', id: 24634 },
      { name: 'MARISOL PATRICIA  ACHA LAURA', id: 10199 },
      { name: 'ARIEL CASTELLON CAZORLA ', id: 18281 },
      { name: 'MARLENE VEIZAGA JATTACO', id: 19698 },
      { name: 'PATRICIA PILAR ZURITA MARTÍNEZ', id: 17209 },
      { name: 'GABRIEL APONTE MEJIA', id: 22087 },
      { name: 'ELVIS JOAQUIN BUSTAMANTE ZOLA', id: 23837 },
      { name: 'RENÉ ROBERTO ZURITA MARTÍNEZ', id: 23780 },
      { name: 'BANIA DORIS VELARDE GARCÍA', id: 13944 },
      { name: 'LUCY  PÉREZ FORONDA', id: 11009 },
      { name: 'JANETH LETICIA MAMANI QUISPE', id: 28934 },
      { name: 'MARIA DELFI  CATARI GUERRERO', id: 16214 },
      { name: 'BRAULIA TRONCOSO TORREZ', id: 18469 },
      { name: 'MAGALY QUISPE TORRICO', id: 16083 },
      { name: 'MARTHA VILLARROEL VALDIVIA', id: 21580 },
      { name: 'MARÍA DEL ROSARIO CAMACHO BALDERRAMA DE ARANDIA', id: 29592 },
      { name: 'DULCE MARIA  CHOQUE ESPADA ', id: 14937 },
      { name: 'NELVY SARAH  RAMALLO MELGAR ', id: 14847 },
      { name: 'BLANCA MOYA FUENTES', id: 24436 },
      { name: 'JHERY WALDO PINTO CLAROS', id: 15157 },
      { name: 'VANIA DAYSI CUEVAS CUEVAS', id: 19601 },
      { name: 'VERONICA GUTIERREZ AÑEZ', id: 20877 },
      { name: 'JUAN  GUTIERREZ CARRILLO', id: 18983 },
      { name: 'VERÓNICA  ADRIAZOLA MURIEL', id: 10894 },
      { name: 'CLAUDIA ABASTO LÓPEZ ', id: 23420 },
      { name: 'ANDREA TASTACA GASPAR', id: 10138 },
      { name: 'JUANA COLQUE ', id: 27772 },
      { name: 'FILIBERTO CAMARGO FERNANDEZ', id: 24429 },
      { name: 'BERTHA COPAGIRA VILLCA', id: 20855 },
      { name: 'MARGARITA  VALENCIA RODRÍGUEZ', id: 16111 },
      { name: 'HECTOR FAVIAN  ESPINOZA CASTILLO', id: 28396 },
      { name: 'TEREZA JAQUELINE FERREL SORIA GALVARRO', id: 20950 },
      { name: 'JHONNY LOPEZ VIDAL', id: 10964 },
      { name: 'GRISELDA  NAVIA  TASTACA ', id: 14171 },
      { name: 'EDWARD LUNA RICALDI', id: 14157 }
    ]
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
})
